services:
  kuznetsova:
    build: .
    container_name: kuznetsova
    restart: always

    env_file:
      - .env.production

    networks:
      - web

networks:
  web:
    name: onlinebazar_app-network
    external: true